spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd
  http:
    encoding:
      charset: UTF-8
      force: true
      force-request: true
      force-response: true
  jackson:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: mapper/*Mapper.xml
server:
  port: 8888
  #  项目名
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
logging:
  pattern:
    console:  '[%p] [%d{yyyy-MM-dd HH:mm:ss}] %c %m %n'
  level:
    root: error
    com.baizhi.dao: debug
